import type {
  AppData,
  CollectionPoint,
  CollectionSchedule,
  GreenPartnerStore,
  Invoice,
  Material,
  Notification,
  PointsHistory,
  PurchaseOrder,
  RecyclingCompany,
  RewardItem,
  Role,
  TruckLocation,
} from "./types";

export const seedMaterials: Material[] = [
  { id: "plastic", name: "بلاستيك", icon: "🧴", color: "#4eaa34", unit: "كجم" },
  { id: "carton", name: "كرتون", icon: "📦", color: "#d28a2d", unit: "كجم" },
  { id: "battery", name: "بطاريات", icon: "🔋", color: "#3b82f6", unit: "كجم" },
  {
    id: "printer_cartridge",
    name: "خرطوشة طابعة",
    icon: "🖨️",
    color: "#8b5cf6",
    unit: "قطعة",
  },
];

export const seedCollectionPoints: CollectionPoint[] = [
  {
    id: "p1",
    name: "منزل أحمد بن يوسف",
    accountName: "أحمد بن يوسف",
    address: "علي منجلي",
    lat: 36.2452,
    lng: 6.5703,
    materials: ["plastic", "carton"],
    status: "completed",
    order: 1,
    quantityMode: "kg",
    quantityValue: 34,
  },
  {
    id: "p2",
    name: "مطعم البركة",
    accountName: "مطعم البركة",
    address: "سيدي مبروك",
    lat: 36.3492,
    lng: 6.6336,
    materials: ["plastic", "carton", "battery"],
    status: "completed",
    order: 2,
    quantityMode: "kg",
    quantityValue: 18,
  },
  {
    id: "p3",
    name: "حي المنظر الجميل",
    accountName: "حي المنظر الجميل",
    address: "قسنطينة وسط",
    lat: 36.365,
    lng: 6.6147,
    materials: ["plastic", "carton", "printer_cartridge"],
    status: "upcoming",
    order: 3,
    quantityMode: "bottles",
    quantityValue: 220,
  },
  {
    id: "p4",
    name: "مدرسة ابن باديس",
    accountName: "مدرسة ابن باديس",
    address: "الخروب",
    lat: 36.2635,
    lng: 6.6932,
    materials: ["plastic", "battery", "carton"],
    status: "upcoming",
    order: 4,
    quantityMode: "bottles",
    quantityValue: 300,
  },
  {
    id: "p5",
    name: "سكن عمار بن عبد المالك",
    accountName: "عمار بن عبد المالك",
    address: "بوصوف",
    lat: 36.346,
    lng: 6.6401,
    materials: ["plastic", "carton"],
    status: "upcoming",
    order: 5,
    quantityMode: "kg",
    quantityValue: 42,
  },
  {
    id: "p6",
    name: "منزل فاطمة الزهراء",
    accountName: "فاطمة الزهراء",
    address: "عين الباي",
    lat: 36.2875,
    lng: 6.6204,
    materials: ["battery", "printer_cartridge"],
    status: "upcoming",
    order: 6,
    quantityMode: "kg",
    quantityValue: 15,
  },
];

export const seedRecyclingCompanies: RecyclingCompany[] = [
  {
    id: "rc1",
    name: "شركة نوميديا للبلاستيك المعاد",
    address: "الخروب",
    lat: 36.2635,
    lng: 6.6932,
    specialty: "بلاستيك",
  },
  {
    id: "rc2",
    name: "شركة قسنطينة للكرتون الصناعي",
    address: "بوصوف",
    lat: 36.346,
    lng: 6.6401,
    specialty: "كرتون",
  },
  {
    id: "rc3",
    name: "شركة البطاريات الخضراء",
    address: "عين الباي",
    lat: 36.2875,
    lng: 6.6204,
    specialty: "بطاريات",
  },
  {
    id: "rc4",
    name: "مخبر خرطوشة بلس",
    address: "الزواغي",
    lat: 36.339,
    lng: 6.6602,
    specialty: "خراطيش طابعة",
  },
  {
    id: "rc5",
    name: "مركز إنك ريسايكل",
    address: "علي منجلي",
    lat: 36.2508,
    lng: 6.575,
    specialty: "خراطيش ",
  },
  {
    id: "rc6",
    name: "مصنع الأثر الدائم",
    address: "جامعة الأمير عبد القادر",
    lat: 36.3477,
    lng: 6.6264,
    specialty: "فرز متعدد",
  },
];

export const seedTrucks: TruckLocation[] = [
  {
    id: "t1",
    name: " CERCLY 01",
    lat: 36.328,
    lng: 6.623,
    status: "loading",
  },
  {
    id: "t2",
    name: " CERCLY 02",
    lat: 36.278,
    lng: 6.612,
    status: "en_route",
  },
  {
    id: "t3",
    name: " CERCLY 03",
    lat: 36.3592,
    lng: 6.604,
    status: "delivered",
  },
];

export function generateOrderId(): string {
  const num = Math.floor(Math.random() * 9000) + 1000;
  return `INV-${num}`;
}

export function generateShipmentId(): string {
  const num = Math.floor(Math.random() * 900) + 100;
  return `SHP-${num}`;
}

export function generateCollectionId(): string {
  return `COL-${Date.now()}`;
}

export function generateInvoiceNumber(): string {
  const num = Math.floor(Math.random() * 90000) + 10000;
  return `CRL-${num}`;
}

let notifCounter = 0;
export function generateNotifId(): string {
  notifCounter += 1;
  return `n-${notifCounter}`;
}

export function formatTimestamp(date: Date): { date: string; time: string } {
  const now = date;
  const h = now.getHours().toString().padStart(2, "0");
  const m = now.getMinutes().toString().padStart(2, "0");
  const day = now.getDate().toString().padStart(2, "0");
  const month = (now.getMonth() + 1).toString().padStart(2, "0");
  return { date: `${day}/${month}`, time: `${h}:${m}` };
}

export function formatTimeAgo(date: Date): string {
  const diff = Date.now() - date.getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "الآن";
  if (mins < 60) return `منذ ${mins} دقيقة`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `منذ ${hours} ساعة`;
  const days = Math.floor(hours / 24);
  return `منذ ${days} يوم`;
}

const roleNames = {
  sorter: "مركز الفرز",
  collector: "جامع",
  factory: "مصنع التدوير",
  partner: "فرد / مؤسسة",
  admin: "الإدارة",
};

const roleAvatars = {
  sorter: "فر",
  collector: "جم",
  factory: "دو",
  partner: "شر",
  admin: "إد",
};

export const seedSchedules: CollectionSchedule[] = [
  {
    id: "sch-1",
    partnerId: "u4",
    pointId: "p3",
    pointName: "حي المنظر الجميل",
    address: "قسنطينة وسط",
    scheduledDate: "غداً",
    scheduledTime: "14:30",
    status: "pending",
    quantityMode: "bottles",
    quantityValue: 220,
  },
  {
    id: "sch-2",
    partnerId: "u5",
    pointId: "p4",
    pointName: "مدرسة ابن باديس",
    address: "الخروب",
    scheduledDate: "15/06",
    scheduledTime: "11:00",
    status: "confirmed",
    quantityMode: "kg",
    quantityValue: 26,
  },
  {
    id: "sch-3",
    partnerId: "u7",
    pointId: "p5",
    pointName: "سكن عمار بن عبد المالك",
    address: "بوصوف",
    scheduledDate: "17/06",
    scheduledTime: "09:00",
    status: "pending",
    quantityMode: "kg",
    quantityValue: 42,
  },
];

const seedOrders: PurchaseOrder[] = [
  {
    id: "INV-2026-0042",
    factoryId: "f1",
    factoryName: "شركة نوميديا للبلاستيك المعاد",
    centerId: "sc1",
    centerName: "مركز فرز قسنطينة",
    materialId: "plastic",
    materialName: "بلاستيك",
    quantity: 1200,
    status: "pending",
    createdAt: "اليوم",
  },
  {
    id: "INV-2026-0038",
    factoryId: "f2",
    factoryName: "شركة قسنطينة للكرتون الصناعي",
    centerId: "sc1",
    centerName: "مركز فرز قسنطينة",
    materialId: "carton",
    materialName: "كرتون",
    quantity: 850,
    status: "confirmed",
    createdAt: "أمس",
  },
  {
    id: "INV-2026-0031",
    factoryId: "f3",
    factoryName: "شركة البطاريات الخضراء",
    centerId: "sc1",
    centerName: "مركز فرز قسنطينة",
    materialId: "battery",
    materialName: "بطاريات",
    quantity: 340,
    status: "confirmed",
    createdAt: "أمس",
  },
];

const seedInvoices: Invoice[] = [
  {
    id: "invoice-1",
    orderId: "INV-2026-0038",
    invoiceNumber: "CRL-54012",
    date: "10/06/2026",
    companyName: "شركة قسنطينة للكرتون الصناعي",
    materialName: "كرتون",
    quantity: 850,
    unitPrice: 48,
    totalPrice: 40800,
    completed: true,
  },
  {
    id: "invoice-2",
    orderId: "INV-2026-0031",
    invoiceNumber: "CRL-54018",
    date: "10/06/2026",
    companyName: "شركة البطاريات الخضراء",
    materialName: "بطاريات",
    quantity: 340,
    unitPrice: 135,
    totalPrice: 45900,
    completed: true,
  },
];

const seedGreenStores: GreenPartnerStore[] = [
  {
    id: "gs1",
    name: "مكتبة النجاح الخضراء",
    address: "علي منجلي",
    description: "مكتبة ومتجر مستلزمات ",
    offers: ["قسائم شرائية", "خصم 15% لأعضاء CERCLY"],
  },
  {
    id: "gs2",
    name: "Green Market",
    address: "قسنطينة وسط",
    description: "متجر مواد غذائية عضوية وطبيعية",
    offers: ["هدايا مجانية", "خصم 20% على المنتجات الخضراء"],
  },
  {
    id: "gs3",
    name: "Eco Store",
    address: "سيدي مبروك",
    description: "متجر منتجات   ",
    offers: ["هدايا ترويجية", "نقاط مضاعفة"],
  },
  {
    id: "gs4",
    name: "Nature Shop",
    address: "الخروب",
    description: "متجر مستلزمات طبيعية وعضوية",
    offers: ["قسائم خصم", "عروض حصرية"],
  },
];

const seedPointsHistory: PointsHistory[] = [
  {
    id: "ph1",
    points: 50,
    reason: "جمع بلاستيك (5 كجم)",
    date: "10/06/2026",
    type: "earned",
  },
  {
    id: "ph2",
    points: 120,
    reason: "جمع بطاريات (5 قطع)",
    date: "08/06/2026",
    type: "earned",
  },
  {
    id: "ph3",
    points: 100,
    reason: "استبدال ميدالية CERCLY",
    date: "05/06/2026",
    type: "redeemed",
  },
  {
    id: "ph4",
    points: 35,
    reason: "جمع كرتون (5 كجم)",
    date: "01/06/2026",
    type: "earned",
  },
  {
    id: "ph5",
    points: 200,
    reason: "جمع خراطيش طابعة (4 قطع)",
    date: "28/05/2026",
    type: "earned",
  },
  {
    id: "ph6",
    points: 150,
    reason: "استبدال قسيمة خصم 15%",
    date: "25/05/2026",
    type: "redeemed",
  },
];

const seedRewards: RewardItem[] = [
  {
    id: "rw1",
    name: "ميدالية CERCLY",
    pointsCost: 100,
    storeName: "مكتبة النجاح الخضراء",
    category: "هدايا",
  },
  {
    id: "rw2",
    name: "حقيبة تسوق CERCLY",
    pointsCost: 200,
    storeName: "Green Market",
    category: "أدوات يومية",
  },
  {
    id: "rw3",
    name: "وسام الشريك الفضي",
    pointsCost: 350,
    storeName: "Eco Store",
    category: "شهادات",
  },
  {
    id: "rw4",
    name: "قسيمة خصم 25%",
    pointsCost: 250,
    storeName: "Nature Shop",
    category: "قسائم",
  },
  {
    id: "rw5",
    name: "قسيمة خصم 15%",
    pointsCost: 150,
    storeName: "Green Market",
    category: "قسائم",
  },
  {
    id: "rw6",
    name: "هدية صديقة للبيئة",
    pointsCost: 180,
    storeName: "Eco Store",
    category: "هدايا",
  },
];

export const seedData: AppData = {
  materials: seedMaterials,
  collectionPoints: seedCollectionPoints,
  schedules: seedSchedules,
  recyclingCompanies: seedRecyclingCompanies,
  trucks: seedTrucks,
  rewards: seedRewards,
  invoices: seedInvoices,
  pointsHistory: seedPointsHistory,
  greenPartnerStores: seedGreenStores,
  collectorEarnings: 0,
  collections: [
    {
      id: "COL-1",
      collectorId: "u2",
      pointId: "p1",
      pointName: "منزل أحمد بن يوسف",
      registeredUserName: "أحمد بن يوسف",
      weight: 280,
      materials: ["plastic", "carton"],
      timestamp: new Date().toISOString(),
      date: "اليوم",
      time: "09:30",
    },
    {
      id: "COL-2",
      collectorId: "u3",
      pointId: "p2",
      pointName: "مطعم البركة",
      registeredUserName: "مطعم البركة",
      weight: 95,
      materials: ["battery", "plastic"],
      timestamp: new Date().toISOString(),
      date: "اليوم",
      time: "11:00",
      bottleCount: 0,
    },
    {
      id: "COL-3",
      collectorId: "u6",
      pointId: "p3",
      pointName: "حي المنظر الجميل",
      registeredUserName: "حي المنظر الجميل",
      weight: 320,
      materials: ["plastic", "carton", "printer_cartridge"],
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      date: "أمس",
      time: "14:00",
    },
    {
      id: "COL-4",
      collectorId: "u2",
      pointId: "p4",
      pointName: "مدرسة ابن باديس",
      registeredUserName: "مدرسة ابن باديس",
      weight: 150,
      materials: ["plastic", "battery"],
      timestamp: new Date(Date.now() - 172800000).toISOString(),
      date: "12/06",
      time: "10:30",
      bottleCount: 300,
    },
  ],
  inventory: [
    {
      centerId: "sc1",
      centerName: "مركز فرز قسنطينة",
      location: "قسنطينة وسط",
      items: [
        {
          materialId: "plastic",
          quantity: 1240,
          capacity: 2200,
          lastReceived: 280,
          lastReceivedLabel: "تم استلام البلاستيك من جامع أحمد",
        },
        {
          materialId: "carton",
          quantity: 890,
          capacity: 1800,
          lastReceived: 180,
          lastReceivedLabel: "تم استلام الكرتون من جامع خالد",
        },
        {
          materialId: "battery",
          quantity: 320,
          capacity: 900,
          lastReceived: 95,
          lastReceivedLabel: "تم استلام البطاريات من جامع أيمن",
        },
        {
          materialId: "printer_cartridge",
          quantity: 140,
          capacity: 450,
          lastReceived: 30,
          lastReceivedLabel: "تم استلام خراطيش الطابعة من حي المنظر الجميل",
        },
      ],
    },
  ],
  orders: seedOrders,
  shipments: [
    {
      id: "SHP-112",
      orderId: "INV-2026-0038",
      fromCenter: "مركز فرز قسنطينة",
      materialName: "كرتون",
      quantity: 850,
      eta: "غداً 10:00",
      status: "in_transit",
    },
    {
      id: "SHP-110",
      orderId: "INV-2026-0031",
      fromCenter: "مركز فرز قسنطينة",
      materialName: "بطاريات",
      quantity: 340,
      eta: "15/06 09:30",
      status: "scheduled",
    },
  ],
  notifications: [
    // Partner
    {
      id: "np1",
      icon: "📦",
      title: "طلب جمع جديد",
      text: "تم إنشاء طلب جمع جديد بنجاح",
      time: "منذ 5 دقائق",
      isNew: true,
      type: "success",
      role: "partner",
    },
    {
      id: "np2",
      icon: "🏍️",
      title: "قبول الطلب",
      text: "تم قبول طلبك من طرف جامع أحمد",
      time: "منذ 18 دقيقة",
      isNew: true,
      type: "info",
      role: "partner",
    },
    {
      id: "np3",
      icon: "📍",
      title: "في الطريق",
      text: "جامع في طريقه إلى موقعك",
      time: "منذ 32 دقيقة",
      isNew: true,
      type: "info",
      role: "partner",
    },
    {
      id: "np4",
      icon: "♻",
      title: "تم الاستلام",
      text: "تم استلام المواد في مركز فرز قسنطينة",
      time: "منذ ساعة",
      isNew: true,
      type: "success",
      role: "partner",
    },
    // Collector
    {
      id: "nc1",
      icon: "📥",
      title: "طلب جمع",
      text: "طلب جمع جديد متاح بالقرب منك",
      time: "منذ 3 دقائق",
      isNew: true,
      type: "info",
      role: "collector",
    },
    {
      id: "nc2",
      icon: "📍",
      title: "مهمة جديدة",
      text: "تم تعيين مهمة جمع جديدة لك",
      time: "منذ 10 دقائق",
      isNew: true,
      type: "success",
      role: "collector",
    },
    {
      id: "nc3",
      icon: "🏍️",
      title: "توجيه",
      text: "توجه إلى مطعم البركة - علي منجلي",
      time: "منذ 15 دقيقة",
      isNew: true,
      type: "info",
      role: "collector",
    },
    {
      id: "nc4",
      icon: "📦",
      title: "تم الاستلام",
      text: "تم تأكيد استلام المواد من المزود",
      time: "منذ 25 دقيقة",
      isNew: true,
      type: "success",
      role: "collector",
    },
    // Sorter
    {
      id: "ns1",
      icon: "🏍️",
      title: "شحنة واردة",
      text: "شحنة جديدة في انتظار الاستلام",
      time: "منذ 5 دقائق",
      isNew: true,
      type: "info",
      role: "sorter",
    },
    {
      id: "ns2",
      icon: "📦",
      title: "تم الاستلام",
      text: "تم استلام المواد من جامع أحمد",
      time: "منذ 12 دقيقة",
      isNew: true,
      type: "success",
      role: "sorter",
    },
    {
      id: "ns3",
      icon: "⚖",
      title: "تحقق من الوزن",
      text: "يرجى التحقق من وزن الشحنة",
      time: "منذ 20 دقيقة",
      isNew: true,
      type: "warning",
      role: "sorter",
    },
    {
      id: "ns4",
      icon: "♻",
      title: "تحديث المخزون",
      text: "تمت إضافة المواد إلى المخزون",
      time: "منذ 35 دقيقة",
      isNew: true,
      type: "success",
      role: "sorter",
    },
    // Factory
    {
      id: "nf1",
      icon: "📦",
      title: "مخزون متاح",
      text: "تم تحديث المخزون المتاح للشراء",
      time: "منذ 5 دقائق",
      isNew: true,
      type: "info",
      role: "factory",
    },
    {
      id: "nf2",
      icon: "🏭",
      title: "مواد متاحة",
      text: "توجد كمية جديدة من البلاستيك متاحة",
      time: "منذ 15 دقيقة",
      isNew: true,
      type: "info",
      role: "factory",
    },
    {
      id: "nf3",
      icon: "📄",
      title: "تم الإرسال",
      text: "تم إرسال طلب الشراء بنجاح",
      time: "منذ 30 دقيقة",
      isNew: true,
      type: "success",
      role: "factory",
    },
    {
      id: "nf4",
      icon: "⏳",
      title: "قيد المراجعة",
      text: "طلب الشراء قيد المراجعة",
      time: "منذ 45 دقيقة",
      isNew: true,
      type: "warning",
      role: "factory",
    },
    // Admin
    {
      id: "na1",
      icon: "👤",
      title: "مستخدم جديد",
      text: "تم تسجيل مستخدم جديد",
      time: "منذ 5 دقائق",
      isNew: true,
      type: "system",
      role: "admin",
    },
    {
      id: "na2",
      icon: "📦",
      title: "طلب جمع",
      text: "تم إنشاء طلب جمع جديد",
      time: "منذ 12 دقيقة",
      isNew: true,
      type: "info",
      role: "admin",
    },
    {
      id: "na3",
      icon: "🏍️",
      title: "عملية جمع",
      text: "تم تنفيذ عملية جمع جديدة",
      time: "منذ 20 دقيقة",
      isNew: true,
      type: "success",
      role: "admin",
    },
    {
      id: "na4",
      icon: "♻",
      title: "تحديث المخزون",
      text: "تم تحديث المخزون",
      time: "منذ 35 دقيقة",
      isNew: true,
      type: "system",
      role: "admin",
    },
  ],
  partnerProfile: {
    name: "أحمد بن يوسف",
    address: "علي منجلي",
    phone: "+213 550 123 456",
    email: "ahmed@cercly.dz",
    level: 4,
    points: 405,
    totalRecycled: 18.4,
    co2Saved: 2.9,
    waterSaved: 4200,
    treesProtected: 28,
    operations: 142,
  },
  users: [
    {
      id: "u1",
      name: "مركز فرز قسنطينة",
      role: "sorter",
      email: "sorter@cercly.dz",
      phone: "+213 31 000 001",
      address: "قسنطينة وسط",
      status: "active",
      joinDate: "2025-01-15",
    },
    {
      id: "u2",
      name: "جامع أحمد",
      role: "collector",
      email: "ahmed.collector@cercly.dz",
      phone: "+213 550 111 111",
      address: "الخروب",
      status: "active",
      joinDate: "2025-02-10",
    },
    {
      id: "u3",
      name: "جامع خالد",
      role: "collector",
      email: "khaled.collector@cercly.dz",
      phone: "+213 550 222 222",
      address: "عين الباي",
      status: "active",
      joinDate: "2025-02-15",
    },
    {
      id: "u6",
      name: "جامع أيمن",
      role: "collector",
      email: "aymen.collector@cercly.dz",
      phone: "+213 550 333 333",
      address: "الزواغي",
      status: "active",
      joinDate: "2025-03-01",
    },
    {
      id: "f1",
      name: "شركة نوميديا للبلاستيك المعاد",
      role: "factory",
      email: "numidia@cercly.dz",
      phone: "+213 31 010 001",
      address: "الخروب",
      status: "active",
      joinDate: "2025-03-01",
    },
    {
      id: "f2",
      name: "شركة قسنطينة للكرتون الصناعي",
      role: "factory",
      email: "carton@cercly.dz",
      phone: "+213 31 010 002",
      address: "بوصوف",
      status: "active",
      joinDate: "2025-03-05",
    },
    {
      id: "f3",
      name: "شركة البطاريات الخضراء",
      role: "factory",
      email: "battery@cercly.dz",
      phone: "+213 31 010 003",
      address: "عين الباي",
      status: "active",
      joinDate: "2025-03-06",
    },
    {
      id: "f4",
      name: "مخبر خرطوشة بلس",
      role: "factory",
      email: "printer@cercly.dz",
      phone: "+213 31 010 004",
      address: "زواغي",
      status: "active",
      joinDate: "2025-03-07",
    },
    {
      id: "f5",
      name: "مركز إنك ريسايكل",
      role: "factory",
      email: "ink@cercly.dz",
      phone: "+213 31 010 005",
      address: "علي منجلي",
      status: "active",
      joinDate: "2025-03-08",
    },
    {
      id: "f6",
      name: "مصنع الأثر الدائم",
      role: "factory",
      email: "impact@cercly.dz",
      phone: "+213 31 010 006",
      address: "جامعة الأمير عبد القادر",
      status: "active",
      joinDate: "2025-03-09",
    },
    {
      id: "u4",
      name: "أحمد بن يوسف",
      role: "partner",
      email: "ahmed@cercly.dz",
      phone: "+213 550 123 456",
      address: "علي منجلي",
      status: "active",
      joinDate: "2025-04-20",
    },
    {
      id: "u5",
      name: "سارة بوزيان",
      role: "partner",
      email: "sara@cercly.dz",
      phone: "+213 550 888 555",
      address: "سيدي مبروك",
      status: "active",
      joinDate: "2025-05-01",
    },
    {
      id: "u7",
      name: "متجر الحياة",
      role: "partner",
      email: "hayet.market@cercly.dz",
      phone: "+213 31 020 100",
      address: "قسنطينة وسط",
      status: "active",
      joinDate: "2025-05-08",
    },
    {
      id: "u8",
      name: "مدرسة ابن باديس",
      role: "partner",
      email: "ibnbadis@cercly.dz",
      phone: "+213 31 020 200",
      address: "الخروب",
      status: "active",
      joinDate: "2025-05-10",
    },
    {
      id: "u9",
      name: "مطعم البركة",
      role: "partner",
      email: "baraka@cercly.dz",
      phone: "+213 550 444 333",
      address: "سيدي مبروك",
      status: "active",
      joinDate: "2025-05-15",
    },
    {
      id: "u10",
      name: "فاطمة الزهراء",
      role: "partner",
      email: "fatima@cercly.dz",
      phone: "+213 550 777 888",
      address: "عين الباي",
      status: "active",
      joinDate: "2025-05-20",
    },
    {
      id: "u11",
      name: "عمار بن عبد العالي",
      role: "partner",
      email: "ammar@cercly.dz",
      phone: "+213 550 999 000",
      address: "بوصوف",
      status: "active",
      joinDate: "2025-05-25",
    },
  ],
  config: { roleNames, roleAvatars },
  session: { loggedIn: false, currentRole: "sorter", currentTab: "dashboard" },
};
